id: demidynamic
name: DemiDynamic
version: ${version}
main: net.demimine.dynamic.DemiDynamic
author: DemiMine Team
description: Automatically starts/stops servers based on player activity

dependencies:
  - id: luckperms
    optional: true
